using FaultWitness.Core;
using FaultWitness.Platform.Windows;
using System.Runtime.InteropServices;
namespace FaultWitness.Windows.Tests;
public sealed class SystemInventoryTests
{
 private static readonly string[] ForbiddenProjectionNames=["SerialNumber","UUID","PNPDeviceID","MACAddress"];
 [Fact] public void Summary_UsesStableIndexedKeys_AndOmitsUnavailableValues(){var s=new SystemInventorySnapshot([new InventoryGroup("InventoryGroupGraphics",[new("private",[new("InventoryGraphicsName","GPU")]),new("x",[new("InventoryGraphicsName","GPU2")])])]);var x=s.ToSummary();Assert.Equal("GPU",x["InventoryGroupGraphics.0.InventoryGraphicsName"]);Assert.Equal("GPU2",x["InventoryGroupGraphics.1.InventoryGraphicsName"]);}
 [Fact] public async Task Collector_MapsPopulatedMachineAcrossAllGroups(){var f=Full();var s=await new WindowsSystemInventory(f).GetAsync(default);Assert.Equal(6,s.Groups.Count);Assert.Contains("Windows",Vals(s,"InventoryGroupOperatingSystem","InventoryOperatingSystem"));Assert.Contains(RuntimeInformation.ProcessArchitecture.ToString(),Vals(s,"InventoryGroupOperatingSystem","InventoryProcessArchitecture"));Assert.Contains("Ryzen",Vals(s,"InventoryGroupProcessorMemory","InventoryProcessor"));Assert.Contains("32",Vals(s,"InventoryGroupProcessorMemory","InventoryMemoryGiB"));Assert.Contains("Board",Vals(s,"InventoryGroupFirmware","InventoryBoardModel"));Assert.Contains("GPU",Vals(s,"InventoryGroupGraphics","InventoryGraphicsName"));Assert.Contains("BIOS",Vals(s,"InventoryGroupFirmware","InventoryBiosVersion"));Assert.Contains("Disk",Vals(s,"InventoryGroupStorage","InventoryStorageModel"));Assert.Contains("Acme",Vals(s,"InventoryGroupDrivers","InventoryDriverProvider"));}
 [Fact] public async Task Collector_MissingBiosValueIsUnavailable(){var f=Full();f.Rows["Win32_BIOS"]=[R(("Manufacturer","Acme"))];var s=await new WindowsSystemInventory(f).GetAsync(default);Assert.Equal(InventoryAvailability.Unavailable,Field(s,"InventoryGroupFirmware","InventoryBiosVersion").Availability);}
 [Fact] public async Task Collector_RetainsMultipleGpus(){var f=Full();f.Rows["Win32_VideoController"]=[R(("Name","GPU A")),R(("Name","GPU B"))];var s=await new WindowsSystemInventory(f).GetAsync(default);Assert.Equal(["GPU A","GPU B"],Fields(s,"InventoryGroupGraphics","InventoryGraphicsName"));}
 [Fact] public async Task Collector_RetainsMultipleDisks(){var f=Full();f.Rows["Win32_DiskDrive"]=[R(("Model","Disk A"),("Size","1073741824")),R(("Model","Disk B"),("Size","2147483648"))];var s=await new WindowsSystemInventory(f).GetAsync(default);Assert.Equal(["Disk A","Disk B"],Fields(s,"InventoryGroupStorage","InventoryStorageModel"));}
 [Fact] public async Task Collector_IsolatesBiosFailure(){var f=Full();f.Fail="Win32_BIOS";var s=await new WindowsSystemInventory(f).GetAsync(default);Assert.Contains("Windows",Vals(s,"InventoryGroupOperatingSystem","InventoryOperatingSystem"));Assert.Contains("Disk",Vals(s,"InventoryGroupStorage","InventoryStorageModel"));}
 [Fact] public async Task Collector_DeniedQueryMapsAccessDenied(){var f=Full();f.Deny="Win32_VideoController";var s=await new WindowsSystemInventory(f).GetAsync(default);Assert.Equal(InventoryAvailability.AccessDenied,Field(s,"InventoryGroupGraphics","InventoryGraphicsName").Availability);}
 [Fact] public async Task Collector_CancellationDuringPendingProviderPropagates(){var f=Full();f.Block="Win32_VideoController";using var c=new CancellationTokenSource();var p=new WindowsSystemInventory(f).GetAsync(c.Token);await f.Started.Task;c.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>p);}
 [Fact] public async Task Collector_QueriesUsePrivacyAllowlistedProjections(){var f=Full();var s=await new WindowsSystemInventory(f).GetAsync(default);Assert.All(f.Queries,q=>{Assert.DoesNotContain("SELECT *",q,StringComparison.OrdinalIgnoreCase);foreach(var z in ForbiddenProjectionNames)Assert.DoesNotContain(z,q,StringComparison.OrdinalIgnoreCase);});Assert.DoesNotContain(s.ToSummary().Values,v=>v.Contains("secret",StringComparison.OrdinalIgnoreCase));}
 [Fact] public async Task Collector_UnknownPropertiesRemainUnavailable(){var f=Full();f.Rows["Win32_VideoController"]=[R(("Name","GPU"),("Secret","secret"))];var s=await new WindowsSystemInventory(f).GetAsync(default);Assert.Equal(InventoryAvailability.Unavailable,Field(s,"InventoryGroupGraphics","InventoryGraphicsDriverVersion").Availability);Assert.DoesNotContain(s.ToSummary().Values,v=>v.Contains("secret"));}
 static Fake Full()=>new(){Rows=new(){["Win32_OperatingSystem"]=[R(("Caption","Windows"),("OSArchitecture","X64"))],["Win32_Processor"]=[R(("Name","Ryzen"))],["Win32_ComputerSystem"]=[R(("Manufacturer","Acme"),("Model","Desk"),("TotalPhysicalMemory","34359738368"))],["Win32_VideoController"]=[R(("Name","GPU"))],["Win32_BaseBoard"]=[R(("Manufacturer","Acme"),("Product","Board"))],["Win32_BIOS"]=[R(("Manufacturer","Acme"),("SMBIOSBIOSVersion","BIOS"))],["Win32_DiskDrive"]=[R(("Model","Disk"),("Size","549755813888"))],["Win32_PnPSignedDriver"]=[R(("DeviceName","Driver"),("DriverProviderName","Acme"),("DeviceClass","DISPLAY"))]}};
 static WindowsInventoryRow R(params(string K,object? V)[] x)=>new(x.ToDictionary(a=>a.K,a=>a.V));static string[] Fields(SystemInventorySnapshot s,string g,string k)=>s.Groups.Single(a=>a.Key==g).Devices.SelectMany(a=>a.Fields).Where(a=>a.Key==k&&a.Value!=null).Select(a=>a.Value!).ToArray();static string Vals(SystemInventorySnapshot s,string g,string k)=>string.Join("|",Fields(s,g,k));static InventoryField Field(SystemInventorySnapshot s,string g,string k)=>s.Groups.Single(a=>a.Key==g).Devices.SelectMany(a=>a.Fields).Single(a=>a.Key==k);
 sealed class Fake:IWindowsInventoryDataSource{public Dictionary<string,IReadOnlyList<WindowsInventoryRow>> Rows{get;set;}=new();public List<string> Queries{get;}=[];public string? Fail,Deny,Block;public TaskCompletionSource Started{get;}=new(TaskCreationOptions.RunContinuationsAsynchronously);public async Task<IReadOnlyList<WindowsInventoryRow>> QueryAsync(string n,string q,CancellationToken t){Queries.Add(q);var c=Rows.Keys.FirstOrDefault(q.Contains)??"";if(c==Block){Started.TrySetResult();await Task.Delay(Timeout.InfiniteTimeSpan,t);}if(c==Deny)throw new UnauthorizedAccessException();if(c==Fail)throw new InvalidOperationException();return Rows.TryGetValue(c,out var r)?r:[];}public Task<IReadOnlyDictionary<string,object?>> ReadRegistryAsync(string s,IReadOnlyList<string> n,CancellationToken t)=>Task.FromResult<IReadOnlyDictionary<string,object?>>(new Dictionary<string,object?>{{"DisplayVersion","24H2"}});}
}
